config/routes.rb
Rails.application.routes.draw do
root 'legislators#index'
  resources :legislators do
    resources :votes
    resources :legislator_comments
  end

  resources :bills do
    resources :bill_comments
  end

  # resources :legislators do
  # end

  resources :votes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :bill_comments
  has_many :votes
  has_many :legislators, through: :votes
end

app/models/bill_comment.rb
class BillComment < ApplicationRecord
  belongs_to :bill
end

app/controllers/bill_comments_controller.rb
class BillCommentsController < ApplicationController
  before_action :set_bill_comment, only: [:show, :edit, :update, :destroy]

  # GET /bill_comments
  # GET /bill_comments.json
  def index
    @bill_comments = BillComment.all
  end

  # GET /bill_comments/1
  # GET /bill_comments/1.json
  def show
  end

  # GET /bill_comments/new
  def new
    @bill_comment = BillComment.new
  end

  # GET /bill_comments/1/edit
  def edit
  end

  # POST /bill_comments
  # POST /bill_comments.json
  def create
    @bill_comment = BillComment.new(bill_comment_params)

    respond_to do |format|
      if @bill_comment.save
        format.html { redirect_to @bill_comment, notice: 'Bill comment was successfully created.' }
        format.json { render :show, status: :created, location: @bill_comment }
      else
        format.html { render :new }
        format.json { render json: @bill_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_comments/1
  # PATCH/PUT /bill_comments/1.json
  def update
    respond_to do |format|
      if @bill_comment.update(bill_comment_params)
        format.html { redirect_to @bill_comment, notice: 'Bill comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_comment }
      else
        format.html { render :edit }
        format.json { render json: @bill_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_comments/1
  # DELETE /bill_comments/1.json
  def destroy
    @bill_comment.destroy
    respond_to do |format|
      format.html { redirect_to bill_comments_url, notice: 'Bill comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_comment
      @bill_comment = BillComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_comment_params
      params.require(:bill_comment).permit(:author, :content)
    end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
    render json: @bills.to_json, status: :ok
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])
    render json: @bill.to_json, status: :ok
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:bill_id, :bill_type, :chamber, :committees, :congress, :history, :introduced, :last_action, :last_vote, :last_version, :official_title, :popular_title, :short_title, :sponsor, :sponsor_bio_id)
    end
end

app/helpers/bill_comments_helper.rb
module BillCommentsHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bill_comments/bills/_form.html.erb
<%= form_for(bill) do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bill_id %>
    <%= f.text_field :bill_id %>
  </div>

  <div class="field">
    <%= f.label :bill_type %>
    <%= f.text_field :bill_type %>
  </div>

  <div class="field">
    <%= f.label :chamber %>
    <%= f.text_field :chamber %>
  </div>

  <div class="field">
    <%= f.label :committees %>
    <%= f.text_field :committees %>
  </div>

  <div class="field">
    <%= f.label :congress %>
    <%= f.number_field :congress %>
  </div>

  <div class="field">
    <%= f.label :history %>
    <%= f.text_field :history %>
  </div>

  <div class="field">
    <%= f.label :introduced %>
    <%= f.date_select :introduced %>
  </div>

  <div class="field">
    <%= f.label :last_action %>
    <%= f.date_select :last_action %>
  </div>

  <div class="field">
    <%= f.label :last_vote %>
    <%= f.date_select :last_vote %>
  </div>

  <div class="field">
    <%= f.label :last_version %>
    <%= f.text_field :last_version %>
  </div>

  <div class="field">
    <%= f.label :official_title %>
    <%= f.text_field :official_title %>
  </div>

  <div class="field">
    <%= f.label :popular_title %>
    <%= f.text_field :popular_title %>
  </div>

  <div class="field">
    <%= f.label :short_title %>
    <%= f.text_field :short_title %>
  </div>

  <div class="field">
    <%= f.label :sponsor %>
    <%= f.text_field :sponsor %>
  </div>

  <div class="field">
    <%= f.label :sponsor_bio_id %>
    <%= f.text_field :sponsor_bio_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_comments/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bill_comments/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table>
  <thead>
    <tr>
      <th>Bill</th>
      <th>Bill type</th>
      <th>Chamber</th>
      <th>Congress</th>
      <th>History</th>
      <th>Introduced</th>
      <th>Last action</th>
      <th>Last vote</th>
      <th>Last version</th>
      <th>Official title</th>
      <th>Popular title</th>
      <th>Short title</th>
      <th>Sponsor</th>
      <th>Sponsor bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.bill_id_from_api %></td>
        <td><%= bill.bill_type %></td>
        <td><%= bill.chamber %></td>
        <td><%= bill.congress %></td>
        <td><%= bill.history %></td>
        <td><%= bill.introduced %></td>
        <td><%= bill.last_action %></td>
        <td><%= bill.last_vote %></td>
        <td><%= bill.last_version %></td>
        <td><%= bill.official_title %></td>
        <td><%= bill.short_title %></td>
        <td><%= JSON.parse(bill.sponsor)["first_name"]+" "+JSON.parse(bill.sponsor)["last_name"] %></td>

        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>
<% console %>

app/views/bill_comments/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path %>

app/views/bill_comments/bills/show.html.erb
<p id="notice"><%= notice %></p>

<% @billcomments.each do |comment| %><p>
    <%= comment.content %>
</p><% end %>

<p>
  <strong>Bill:</strong>
  <%= @bill.bill_id_from_api %>
</p>

<p>
  <strong>Bill type:</strong>
  <%= @bill.bill_type %>
</p>

<p>
  <strong>Chamber:</strong>
  <%= @bill.chamber %>
</p>

<p>
  <strong>Congress:</strong>
  <%= @bill.congress %>
</p>

<p>
  <strong>History:</strong>
  <%= @bill.history %>
</p>

<p>
  <strong>Introduced:</strong>
  <%= @bill.introduced %>
</p>

<p>
  <strong>Last action:</strong>
  <%= @bill.last_action %>
</p>

<p>
  <strong>Last vote:</strong>
  <%= @bill.last_vote %>
</p>

<p>
  <strong>Last version:</strong>
  <%= @bill.last_version %>
</p>

<p>
  <strong>Official title:</strong>
  <%= @bill.official_title %>
</p>

<p>
  <strong>Popular title:</strong>
  <%= @bill.popular_title %>
</p>

<p>
  <strong>Short title:</strong>
  <%= @bill.short_title %>
</p>

<p>
  <strong>Sponsor:</strong>
  <%= @bill.sponsor %>
</p>

<p>
  <strong>Sponsor bio:</strong>
  <%= @bill.sponsor_bio_id %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>