config/routes.rb
Rails.application.routes.draw do
root 'legislators#index'
  resources :legislators do
    resources :votes
    resources :legislator_comments
  end

  resources :bills do
    resources :bill_comments
  end

  # resources :legislators do
  # end

  resources :votes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/legislator_comment.rb
class LegislatorComment < ApplicationRecord
  belongs_to :legislator
end

app/controllers/legislator_comments_controller.rb
class LegislatorCommentsController < ApplicationController
  # AM: Nice!
  before_action :set_legislator_comment, only: [:show, :edit, :update, :destroy]

  # GET /legislator_comments
  # GET /legislator_comments.json
  def index
    @legislator_comments = LegislatorComment.all
  end

  # GET /legislator_comments/1
  # GET /legislator_comments/1.json
  def show
  end

  # GET /legislator_comments/new
  def new
    @legislator_comment = LegislatorComment.new
  end

  # GET /legislator_comments/1/edit
  def edit
  end

  # POST /legislator_comments
  # POST /legislator_comments.json
  def create
    @legislator = Legislator.find(params[:legislator_id])
    @legislator_comment = @legislator.legislator_comments.new(legislator_comment_params)

    # respond_to do |format|
      if @legislator_comment.save
        # format.html { redirect_to @legislator_comment, notice: 'Legislator comment was successfully created.' }
        # format.json {
          render json: @legislator_comment.to_json, status: :created
          # render :show, status: :created, location: @legislator_comment
      else
        binding.pry
        # format.html { render :new }
        # format.json {
        render json: @legislator.to_json, status: :created
      # end
    end
  end

  # PATCH/PUT /legislator_comments/1
  # PATCH/PUT /legislator_comments/1.json
  def update
    respond_to do |format|
      if @legislator_comment.update(legislator_comment_params)
        format.html { redirect_to @legislator_comment, notice: 'Legislator comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @legislator_comment }
      else
        format.html { render :edit }
        format.json { render json: @legislator_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legislator_comments/1
  # DELETE /legislator_comments/1.json
  def destroy
    @legislator_comment.destroy
    respond_to do |format|
      format.html { redirect_to legislator_comments_url, notice: 'Legislator comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legislator_comment
      @legislator_comment = LegislatorComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legislator_comment_params
      params.require(:legislator_comment).permit(:author, :content, :legislator_id)
    end
  end

app/helpers/legislator_comments_helper.rb
module LegislatorCommentsHelper
end

app/views/legislator_comments/_form.html.erb
<%= form_for(legislator_comment) do |f| %>
  <% if legislator_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(legislator_comment.errors.count, "error") %> prohibited this legislator_comment from being saved:</h2>

      <ul>
      <% legislator_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legislator_comments/edit.html.erb
<h1>Editing Legislator Comment</h1>

<%= render 'form', legislator_comment: @legislator_comment %>

<%= link_to 'Show', @legislator_comment %> |
<%= link_to 'Back', legislator_comments_path %>

app/views/legislator_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Legislator Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legislator_comments.each do |legislator_comment| %>
      <tr>
        <td><%= legislator_comment.author %></td>
        <td><%= legislator_comment.content %></td>
        <td><%= link_to 'Show', legislator_comment %></td>
        <td><%= link_to 'Edit', edit_legislator_comment_path(legislator_comment) %></td>
        <td><%= link_to 'Destroy', legislator_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legislator Comment', new_legislator_comment_path %>

app/views/legislator_comments/new.html.erb
<h1>New Legislator Comment</h1>

<%= render 'form', legislator_comment: @legislator_comment %>

<%= link_to 'Back', legislator_comments_path %>

app/views/legislator_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @legislator_comment.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @legislator_comment.content %>
</p>

<%= link_to 'Edit', edit_legislator_comment_path(@legislator_comment) %> |
<%= link_to 'Back', legislator_comments_path %>