config/routes.rb
Rails.application.routes.draw do
root 'legislators#index'
  resources :legislators do
    resources :votes
    resources :legislator_comments
  end

  resources :bills do
    resources :bill_comments
  end

  # resources :legislators do
  # end

  resources :votes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill_comment.rb
class BillComment < ApplicationRecord
  belongs_to :bill
end

app/controllers/bill_comments_controller.rb
class BillCommentsController < ApplicationController
  before_action :set_bill_comment, only: [:show, :edit, :update, :destroy]

  # GET /bill_comments
  # GET /bill_comments.json
  def index
    @bill_comments = BillComment.all
  end

  # GET /bill_comments/1
  # GET /bill_comments/1.json
  def show
  end

  # GET /bill_comments/new
  def new
    @bill_comment = BillComment.new
  end

  # GET /bill_comments/1/edit
  def edit
  end

  # POST /bill_comments
  # POST /bill_comments.json
  def create
    @bill_comment = BillComment.new(bill_comment_params)

    respond_to do |format|
      if @bill_comment.save
        format.html { redirect_to @bill_comment, notice: 'Bill comment was successfully created.' }
        format.json { render :show, status: :created, location: @bill_comment }
      else
        format.html { render :new }
        format.json { render json: @bill_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_comments/1
  # PATCH/PUT /bill_comments/1.json
  def update
    respond_to do |format|
      if @bill_comment.update(bill_comment_params)
        format.html { redirect_to @bill_comment, notice: 'Bill comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_comment }
      else
        format.html { render :edit }
        format.json { render json: @bill_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_comments/1
  # DELETE /bill_comments/1.json
  def destroy
    @bill_comment.destroy
    respond_to do |format|
      format.html { redirect_to bill_comments_url, notice: 'Bill comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_comment
      @bill_comment = BillComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_comment_params
      params.require(:bill_comment).permit(:author, :content)
    end
end

app/helpers/bill_comments_helper.rb
module BillCommentsHelper
end

app/views/bill_comments/_form.html.erb
<%= form_for(bill_comment) do |f| %>
  <% if bill_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill_comment.errors.count, "error") %> prohibited this bill_comment from being saved:</h2>

      <ul>
      <% bill_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_comments/edit.html.erb
<h1>Editing Bill Comment</h1>

<%= render 'form', bill_comment: @bill_comment %>

<%= link_to 'Show', @bill_comment %> |
<%= link_to 'Back', bill_comments_path %>

app/views/bill_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bill Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_comments.each do |bill_comment| %>
      <tr>
        <td><%= bill_comment.author %></td>
        <td><%= bill_comment.content %></td>
        <td><%= link_to 'Show', bill_comment %></td>
        <td><%= link_to 'Edit', edit_bill_comment_path(bill_comment) %></td>
        <td><%= link_to 'Destroy', bill_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill Comment', new_bill_comment_path %>

app/views/bill_comments/new.html.erb
<h1>New Bill Comment</h1>

<%= render 'form', bill_comment: @bill_comment %>

<%= link_to 'Back', bill_comments_path %>

app/views/bill_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @bill_comment.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @bill_comment.content %>
</p>

<%= link_to 'Edit', edit_bill_comment_path(@bill_comment) %> |
<%= link_to 'Back', bill_comments_path %>