config/routes.rb
Rails.application.routes.draw do
root 'legislators#index'
  resources :legislators do
    resources :votes
    resources :legislator_comments
  end

  resources :bills do
    resources :bill_comments
  end

  # resources :legislators do
  # end

  resources :votes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  # belongs_to :legislator
  # belongs_to :bill
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
    # @legislator = Legislator.find(params[:legislator_id])
    # @votes_id = Vote.all.pluck(:voter_ids, :bill_id)
    # @votes = @votes_id.each do |vote|
    #  @legVotes = JSON.parse(vote)
    # end
    render json: @votes.to_json, status: :ok
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @legislator = Legislator.find(params[:legislator_id])
    @vote = Vote.find(params[:id])
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:vote_type, :chamber, :congress, :voted_at, :bill_id, :roll_id, :year, :result)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(vote) do |f| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vote_type %>
    <%= f.text_field :vote_type %>
  </div>

  <div class="field">
    <%= f.label :chamber %>
    <%= f.text_field :chamber %>
  </div>

  <div class="field">
    <%= f.label :congress %>
    <%= f.text_field :congress %>
  </div>

  <div class="field">
    <%= f.label :voted_at %>
    <%= f.date_select :voted_at %>
  </div>

  <div class="field">
    <%= f.label :bill_id %>
    <%= f.text_field :bill_id %>
  </div>

  <div class="field">
    <%= f.label :roll_id %>
    <%= f.text_field :roll_id %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :result %>
    <%= f.text_field :result %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Vote type</th>
      <th>Chamber</th>
      <th>Congress</th>
      <th>Voted at</th>
      <th>Bill</th>
      <th>Roll</th>
      <th>Year</th>
      <th>Result</th>
      <th>Voters</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.vote_type %></td>
        <td><%= vote.chamber %></td>
        <td><%= vote.congress %></td>
        <td><%= vote.voted_at %></td>
        <td><%= vote.bill_id %></td>
        <td><%= vote.roll_id %></td>
        <td><%= vote.year %></td>
        <td><%= vote.result %></td>
        <td><%= vote.voter_ids %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% console %>
<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vote type:</strong>
  <%= @vote.vote_type %>
</p>

<p>
  <strong>Chamber:</strong>
  <%= @vote.chamber %>
</p>

<p>
  <strong>Congress:</strong>
  <%= @vote.congress %>
</p>

<p>
  <strong>Voted at:</strong>
  <%= @vote.voted_at %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @vote.bill_id %>
</p>

<p>
  <strong>Roll:</strong>
  <%= @vote.roll_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vote.year %>
</p>

<p>
  <strong>Result:</strong>
  <%= @vote.result %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>